; Generated by TSN Bootstrap Compiler

declare ptr @class_alloc(i32)
declare void @class_incref(ptr)
declare void @class_decref(ptr, ptr)
declare ptr @Array_new()
declare ptr @Array_get_impl(ptr, i32)
declare void @Array_push_impl(ptr, ptr)
declare i32 @Array_length_impl(ptr)
declare void @tsn_incref(ptr)
declare void @tsn_decref(ptr)
declare ptr @_T_string_concat_P_ptr_ptr(ptr, ptr)
declare i32 @_T_string_equals_P_ptr_ptr(ptr, ptr)
declare void @_T_log_P_ptr(ptr)
declare ptr @_T_readText_P_ptr(ptr)
declare void @_T_writeText_P_ptr_ptr(ptr, ptr)
declare void @print_i32(i32)


define void @main() {
entry:
  call void @_T_log_P_ptr(ptr @.str.0)
  ret void
}

@.str.0 = private unnamed_addr constant { i32, i32, [24 x i8] } { i32 -1, i32 23, [24 x i8] c"Hello from compiler v2!\00" }