; Generated by TSN Bootstrap Compiler

declare ptr @class_alloc(i32)
declare void @class_incref(ptr)
declare void @class_decref(ptr, ptr)
declare ptr @Array_new()
declare ptr @Array_get_impl(ptr, i32)
declare void @Array_push_impl(ptr, ptr)
declare i32 @Array_length_impl(ptr)
declare void @tsn_incref(ptr)
declare void @tsn_decref(ptr)
declare ptr @_T_string_concat_P_ptr_ptr(ptr, ptr)
declare i32 @_T_string_equals_P_ptr_ptr(ptr, ptr)
declare void @_T_log_P_ptr(ptr)
declare ptr @_T_readText_P_ptr(ptr)
declare void @_T_writeText_P_ptr_ptr(ptr, ptr)
declare void @print_i32(i32)
declare i32 @charCodeAt(ptr, i32)
declare ptr @slice(ptr, i32, i32)
declare i32 @tsn_string_length(ptr)

%Expr = type { i32, ptr, ptr, ptr, ptr, ptr, ptr }

define ptr @Expr_new() {
entry:
  %r0 = call ptr @class_alloc(i32 56)
  %r1 = alloca ptr, align 8
  store ptr %r0, ptr %r1, align 8
  %r2 = load ptr, ptr %r1, align 8
  %r3 = getelementptr inbounds %Expr, ptr %r2, i32 0, i32 2
  store ptr @.str.0, ptr %r3, align 8
  %r4 = load ptr, ptr %r1, align 8
  %r5 = getelementptr inbounds %Expr, ptr %r4, i32 0, i32 3
  store ptr @.str.1, ptr %r5, align 8
  %r6 = load ptr, ptr %r1, align 8
  %r7 = getelementptr inbounds %Expr, ptr %r6, i32 0, i32 6
  store ptr @.str.2, ptr %r7, align 8
  ret ptr %r0
}

define ptr @createBinary() {
entry:
  %r0 = call ptr @Expr_new()
  %r1 = alloca ptr, align 8
  store ptr %r0, ptr %r1, align 8
  %r2 = load ptr, ptr %r1, align 8
  %r3 = getelementptr inbounds %Expr, ptr %r2, i32 0, i32 2
  store ptr @.str.3, ptr %r3, align 8
  %r4 = load ptr, ptr %r1, align 8
  %r5 = getelementptr inbounds %Expr, ptr %r4, i32 0, i32 3
  store ptr @.str.4, ptr %r5, align 8
  %r6 = call ptr @Expr_new()
  %r7 = alloca ptr, align 8
  store ptr %r6, ptr %r7, align 8
  %r8 = load ptr, ptr %r7, align 8
  %r9 = getelementptr inbounds %Expr, ptr %r8, i32 0, i32 2
  store ptr @.str.5, ptr %r9, align 8
  %r10 = load ptr, ptr %r7, align 8
  %r11 = getelementptr inbounds %Expr, ptr %r10, i32 0, i32 3
  store ptr @.str.6, ptr %r11, align 8
  %r12 = call ptr @Expr_new()
  %r13 = alloca ptr, align 8
  store ptr %r12, ptr %r13, align 8
  %r14 = load ptr, ptr %r13, align 8
  %r15 = getelementptr inbounds %Expr, ptr %r14, i32 0, i32 2
  store ptr @.str.7, ptr %r15, align 8
  %r16 = load ptr, ptr %r13, align 8
  %r17 = load ptr, ptr %r1, align 8
  %r18 = getelementptr inbounds %Expr, ptr %r16, i32 0, i32 4
  store ptr %r17, ptr %r18, align 8
  %r19 = load ptr, ptr %r13, align 8
  %r20 = load ptr, ptr %r7, align 8
  %r21 = getelementptr inbounds %Expr, ptr %r19, i32 0, i32 5
  store ptr %r20, ptr %r21, align 8
  %r22 = load ptr, ptr %r13, align 8
  %r23 = getelementptr inbounds %Expr, ptr %r22, i32 0, i32 6
  store ptr @.str.8, ptr %r23, align 8
  %r24 = load ptr, ptr %r13, align 8
  ret ptr %r24
}

define i32 @main() {
entry:
  %r0 = call ptr @createBinary()
  %r1 = alloca ptr, align 8
  store ptr %r0, ptr %r1, align 8
  ret i32 42
}

@.str.0 = private unnamed_addr constant { i32, i32, [1 x i8] } { i32 -1, i32 0, [1 x i8] c"\00" }
@.str.1 = private unnamed_addr constant { i32, i32, [1 x i8] } { i32 -1, i32 0, [1 x i8] c"\00" }
@.str.2 = private unnamed_addr constant { i32, i32, [1 x i8] } { i32 -1, i32 0, [1 x i8] c"\00" }
@.str.3 = private unnamed_addr constant { i32, i32, [14 x i8] } { i32 -1, i32 13, [14 x i8] c"NumberLiteral\00" }
@.str.4 = private unnamed_addr constant { i32, i32, [2 x i8] } { i32 -1, i32 1, [2 x i8] c"5\00" }
@.str.5 = private unnamed_addr constant { i32, i32, [14 x i8] } { i32 -1, i32 13, [14 x i8] c"NumberLiteral\00" }
@.str.6 = private unnamed_addr constant { i32, i32, [2 x i8] } { i32 -1, i32 1, [2 x i8] c"7\00" }
@.str.7 = private unnamed_addr constant { i32, i32, [11 x i8] } { i32 -1, i32 10, [11 x i8] c"BinaryExpr\00" }
@.str.8 = private unnamed_addr constant { i32, i32, [2 x i8] } { i32 -1, i32 1, [2 x i8] c"+\00" }