; Generated by TSN Bootstrap Compiler

declare ptr @class_alloc(i32)
declare void @class_incref(ptr)
declare void @class_decref(ptr, ptr)
declare ptr @Array_new()
declare ptr @Array_get_impl(ptr, i32)
declare void @Array_push_impl(ptr, ptr)
declare i32 @Array_length_impl(ptr)
declare void @tsn_incref(ptr)
declare void @tsn_decref(ptr)
declare ptr @_T_string_concat_P_ptr_ptr(ptr, ptr)
declare i32 @_T_string_equals_P_ptr_ptr(ptr, ptr)
declare void @_T_log_P_ptr(ptr)
declare ptr @_T_readText_P_ptr(ptr)
declare void @_T_writeText_P_ptr_ptr(ptr, ptr)
declare void @print_i32(i32)
declare i32 @charCodeAt(ptr, i32)
declare ptr @slice(ptr, i32, i32)
declare i32 @tsn_string_length(ptr)

%Container = type { i32, ptr, ptr }
%Expr = type { i32, ptr, ptr }

define ptr @Container_new() {
entry:
  %r0 = call ptr @class_alloc(i32 24)
  %r1 = alloca ptr, align 8
  store ptr %r0, ptr %r1, align 8
  %r2 = load ptr, ptr %r1, align 8
  %r3 = call ptr @Expr_new()
  %r4 = getelementptr inbounds %Container, ptr %r2, i32 0, i32 2
  store ptr %r3, ptr %r4, align 8
  ret ptr %r0
}

define ptr @Expr_new() {
entry:
  %r0 = call ptr @class_alloc(i32 24)
  %r1 = alloca ptr, align 8
  store ptr %r0, ptr %r1, align 8
  %r2 = load ptr, ptr %r1, align 8
  %r3 = getelementptr inbounds %Expr, ptr %r2, i32 0, i32 2
  store ptr @.str.0, ptr %r3, align 8
  ret ptr %r0
}

define i32 @test() {
entry:
  %r0 = call ptr @Container_new()
  %r1 = alloca ptr, align 8
  store ptr %r0, ptr %r1, align 8
  %r2 = call ptr @Expr_new()
  %r3 = alloca ptr, align 8
  store ptr %r2, ptr %r3, align 8
  %r4 = load ptr, ptr %r1, align 8
  %r5 = load ptr, ptr %r3, align 8
  %r6 = getelementptr inbounds %Container, ptr %r4, i32 0, i32 2
  store ptr %r5, ptr %r6, align 8
  ret i32 42
}

define i32 @main() {
entry:
  %r0 = call ptr @test()
  %r1 = ptrtoint ptr %r0 to i64
  %r2 = trunc i64 %r1 to i32
  ret i32 %r2
}

@.str.0 = private unnamed_addr constant { i32, i32, [1 x i8] } { i32 -1, i32 0, [1 x i8] c"\00" }