; Generated by TSN Bootstrap Compiler

declare ptr @class_alloc(i32)
declare void @class_incref(ptr)
declare void @class_decref(ptr, ptr)
declare ptr @Array_new()
declare ptr @Array_get_impl(ptr, i32)
declare void @Array_push_impl(ptr, ptr)
declare i32 @Array_length_impl(ptr)
declare void @tsn_incref(ptr)
declare void @tsn_decref(ptr)
declare ptr @_T.string_concat$P.ptr.ptr(ptr, ptr)
declare i32 @_T.string_equals$P.ptr.ptr(ptr, ptr)
declare void @_T.log$P.ptr(ptr)
declare ptr @_T.readText$P.ptr(ptr)
declare void @_T.writeText$P.ptr.ptr(ptr, ptr)
declare void @print_i32(i32)

%SourceLocation = type { i32, ptr, i32, i32 }
%Program = type { i32, ptr, ptr }
%FunctionDecl = type { i32, ptr, ptr, ptr, ptr, ptr }
%Parameter = type { i32, ptr, ptr, ptr }
%BlockStmt = type { i32, ptr, ptr }
%Stmt = type { i32, ptr, ptr }
%ReturnStmt = type { i32, ptr, ptr, ptr }
%ExprStmt = type { i32, ptr, ptr, ptr }
%VarDeclStmt = type { i32, ptr, ptr, ptr, ptr, ptr }
%Expr = type { i32, ptr, ptr }
%NumberLiteral = type { i32, ptr, ptr, i32 }
%Identifier = type { i32, ptr, ptr, ptr }
%BinaryExpr = type { i32, ptr, ptr, ptr, ptr, ptr }
%CallExpr = type { i32, ptr, ptr, ptr, ptr }

define i32 @_T.isValidType$P(ptr %typeName) {
entry:
  %0 = alloca ptr, align 8
  store ptr %typeName, ptr %0, align 8
  %1 = load ptr, ptr %0, align 8
  %3 = icmp eq i32 %1, @.str.0
  %2 = zext i1 %3 to i32
  %4 = trunc i32 %2 to i1
  br i1 %4, label %if.then.0, label %if.end.2
if.then.0:
  ret i32 1
if.end.2:
  %5 = load ptr, ptr %0, align 8
  %7 = icmp eq i32 %5, @.str.1
  %6 = zext i1 %7 to i32
  %8 = trunc i32 %6 to i1
  br i1 %8, label %if.then.3, label %if.end.5
if.then.3:
  ret i32 1
if.end.5:
  %9 = load ptr, ptr %0, align 8
  %11 = icmp eq i32 %9, @.str.2
  %10 = zext i1 %11 to i32
  %12 = trunc i32 %10 to i1
  br i1 %12, label %if.then.6, label %if.end.8
if.then.6:
  ret i32 1
if.end.8:
  %13 = load ptr, ptr %0, align 8
  %15 = icmp eq i32 %13, @.str.3
  %14 = zext i1 %15 to i32
  %16 = trunc i32 %14 to i1
  br i1 %16, label %if.then.9, label %if.end.11
if.then.9:
  ret i32 1
if.end.11:
  ret i32 0
}

@.str.0 = private unnamed_addr constant { i32, i32, [4 x i8] } { i32 -1, i32 3, [4 x i8] c"i32\00" }
@.str.1 = private unnamed_addr constant { i32, i32, [4 x i8] } { i32 -1, i32 3, [4 x i8] c"i64\00" }
@.str.2 = private unnamed_addr constant { i32, i32, [5 x i8] } { i32 -1, i32 4, [5 x i8] c"bool\00" }
@.str.3 = private unnamed_addr constant { i32, i32, [5 x i8] } { i32 -1, i32 4, [5 x i8] c"void\00" }