; Generated by TSN Bootstrap Compiler

declare ptr @class_alloc(i32)
declare void @class_incref(ptr)
declare void @class_decref(ptr, ptr)
declare ptr @Array_new()
declare ptr @Array_get_impl(ptr, i32)
declare void @Array_push_impl(ptr, ptr)
declare i32 @Array_length_impl(ptr)
declare void @tsn_incref(ptr)
declare void @tsn_decref(ptr)
declare ptr @_T_string_concat_P_ptr_ptr(ptr, ptr)
declare i32 @_T_string_equals_P_ptr_ptr(ptr, ptr)
declare void @_T_log_P_ptr(ptr)
declare ptr @_T_readText_P_ptr(ptr)
declare void @_T_writeText_P_ptr_ptr(ptr, ptr)
declare void @print_i32(i32)
declare i32 @charCodeAt(ptr, i32)
declare ptr @slice(ptr, i32, i32)
declare i32 @tsn_string_length(ptr)


define i32 @complexAdd(i32 %a, i32 %b, i32 %c) {
entry:
  %r0 = alloca i32, align 8
  store i32 %a, ptr %r0, align 8
  %r1 = alloca i32, align 8
  store i32 %b, ptr %r1, align 8
  %r2 = alloca i32, align 8
  store i32 %c, ptr %r2, align 8
  %r3 = load i32, ptr %r0, align 8
  %r4 = load i32, ptr %r1, align 8
  %r5 = add i32 %r3, %r4
  %r6 = load i32, ptr %r2, align 8
  %r7 = add i32 %r5, %r6
  ret i32 %r7
}

define i32 @nestedMath(i32 %x, i32 %y) {
entry:
  %r0 = alloca i32, align 8
  store i32 %x, ptr %r0, align 8
  %r1 = alloca i32, align 8
  store i32 %y, ptr %r1, align 8
  %r2 = load i32, ptr %r0, align 8
  %r3 = load i32, ptr %r1, align 8
  %r4 = add i32 %r2, %r3
  %r5 = mul i32 %r4, 2
  ret i32 %r5
}
