; Generated by TSN Bootstrap Compiler

declare ptr @class_alloc(i32)
declare void @class_incref(ptr)
declare void @class_decref(ptr, ptr)
declare ptr @Array_new()
declare ptr @Array_get_impl(ptr, i32)
declare void @Array_push_impl(ptr, ptr)
declare i32 @Array_length_impl(ptr)
declare void @tsn_incref(ptr)
declare void @tsn_decref(ptr)
declare ptr @_T_string_concat_P_ptr_ptr(ptr, ptr)
declare i32 @_T_string_equals_P_ptr_ptr(ptr, ptr)
declare void @_T_log_P_ptr(ptr)
declare ptr @_T_readText_P_ptr(ptr)
declare void @_T_writeText_P_ptr_ptr(ptr, ptr)
declare void @print_i32(i32)
declare i32 @charCodeAt(ptr, i32)
declare ptr @slice(ptr, i32, i32)
declare i32 @tsn_string_length(ptr)


define i32 @test() {
entry:
  %r0 = add i32 5, 7
  ret i32 %r0
}

define i32 @main() {
entry:
  %r0 = call i32 @test()
  ret i32 %r0
}
