#!/usr/bin/env pwsh
# Create unified TSN compiler by concatenating all modules

Write-Host "Creating unified TSN compiler..." -ForegroundColor Cyan

$output = @"
// UnifiedCompiler.tsn - Complete TSN compiler in a single file
// Generated by concatenating Types.tsn + Lexer.tsn + Parser.tsn + Codegen.tsn
// This allows self-hosting without implementing module system

// ============================================================================
// TYPES MODULE
// ============================================================================

"@

# Read Types.tsn
Write-Host "  Adding Types.tsn..." -ForegroundColor Yellow
$typesContent = Get-Content "src/Types.tsn" -Raw
$output += $typesContent
$output += "`n`n"

# Read Lexer.tsn (skip first comment lines and fix global variables)
Write-Host "  Adding Lexer.tsn..." -ForegroundColor Yellow
$lexerContent = Get-Content "src/Lexer.tsn" -Raw
# Fix global variables without initializers
$lexerContent = $lexerContent -replace 'let source: ptr<i8>;', 'let source: ptr<i8> = 0;'
$lexerContent = $lexerContent -replace 'let sourceLen: i32;', 'let sourceLen: i32 = 0;'
$lexerContent = $lexerContent -replace 'let tokens: Token\[10000\];', 'let tokens: Token[10000] = 0;'
$lexerContent = $lexerContent -replace 'let tokenCount: i32;', 'let tokenCount: i32 = 0;'
$lexerContent = $lexerContent -replace 'let pos: i32;', 'let pos: i32 = 0;'
$lexerContent = $lexerContent -replace 'let line: i32;', 'let line: i32 = 0;'
$lexerContent = $lexerContent -replace 'let column: i32;', 'let column: i32 = 0;'
# Remove first 3 comment lines
$lexerLines = $lexerContent -split "`n"
$lexerFiltered = $lexerLines[3..($lexerLines.Length-1)] -join "`n"
$output += "// ============================================================================`n"
$output += "// LEXER MODULE`n"
$output += "// ============================================================================`n`n"
$output += $lexerFiltered
$output += "`n`n"

# Add missing global declarations for parser (nodes array, nodeCount)
$output += "// ============================================================================`n"
$output += "// PARSER GLOBALS (defined here for unified compilation)`n"
$output += "// ============================================================================`n`n"
$output += "let nodes: ASTNode[5000] = 0;`n"
$output += "let nodeCount: i32 = 0;`n`n"

# Read Parser.tsn (skip first comment lines)
Write-Host "  Adding Parser.tsn..." -ForegroundColor Yellow
$parserContent = Get-Content "src/Parser.tsn" -Raw
# Rename parser's advance() to parser_advance() to avoid clash with lexer's advance()
# Must replace call sites too, but only the plain "advance()" token (not "lexer_advance" etc.)
$parserContent = $parserContent -replace '\bfunction advance\(\)', 'function parser_advance()'
$parserContent = $parserContent -replace '\badvance\(\)', 'parser_advance()'
$parserLines = $parserContent -split "`n"
$parserFiltered = $parserLines[3..($parserLines.Length-1)] -join "`n"
$output += "// ============================================================================`n"
$output += "// PARSER MODULE`n"
$output += "// ============================================================================`n`n"
$output += $parserFiltered
$output += "`n`n"

# Read Codegen.tsn (skip first comment lines and fix global arrays)
Write-Host "  Adding Codegen.tsn..." -ForegroundColor Yellow
$codegenContent = Get-Content "src/Codegen.tsn" -Raw
# Fix global arrays without initializers - add dummy initializer
$codegenContent = $codegenContent -replace 'let output: i32\[500000\];', 'let output: i32[500000] = 0;'
$codegenContent = $codegenContent -replace 'let loopBreakLabels: i32\[10\];', 'let loopBreakLabels: i32[10] = 0;'
$codegenContent = $codegenContent -replace 'let loopContinueLabels: i32\[10\];', 'let loopContinueLabels: i32[10] = 0;'
$codegenContent = $codegenContent -replace 'let structNames: i32\[100\];', 'let structNames: i32[100] = 0;'
$codegenContent = $codegenContent -replace 'let structFieldCounts: i32\[100\];', 'let structFieldCounts: i32[100] = 0;'
$codegenContent = $codegenContent -replace 'let globalNames: i32\[100\];', 'let globalNames: i32[100] = 0;'
$codegenContent = $codegenContent -replace 'let globalTypes: i32\[100\];', 'let globalTypes: i32[100] = 0;'
$codegenContent = $codegenContent -replace 'let globalIsConst: i32\[100\];', 'let globalIsConst: i32[100] = 0;'
$codegenContent = $codegenContent -replace 'let stringLiteralValues: i32\[100\];', 'let stringLiteralValues: i32[100] = 0;'
$codegenContent = $codegenContent -replace 'let stringLiteralNames: i32\[100\];', 'let stringLiteralNames: i32[100] = 0;'
$codegenContent = $codegenContent -replace 'let currentFunctionParamNames: i32\[20\];', 'let currentFunctionParamNames: i32[20] = 0;'
$codegenLines = $codegenContent -split "`n"
$codegenFiltered = $codegenLines[4..($codegenLines.Length-1)] -join "`n"
$output += "// ============================================================================`n"
$output += "// CODEGEN MODULE`n"
$output += "// ============================================================================`n`n"
$output += $codegenFiltered
$output += "`n`n"

# Add main function
$output += @"
// ============================================================================
// MAIN ENTRY POINT - Full self-hosting compiler
// ============================================================================

// C stdlib FFI declarations
declare function fopen(filename: ptr<i8>, mode: ptr<i8>): ptr<i8>;
declare function fclose(file: ptr<i8>): i32;
declare function fread(buf: ptr<i8>, size: i32, count: i32, file: ptr<i8>): i32;
declare function fwrite(buf: ptr<i8>, size: i32, count: i32, file: ptr<i8>): i32;
declare function puts(str: ptr<i8>): i32;
declare function putchar(c: i32): i32;
declare function stderr_puts(str: ptr<i8>): i32;

// Global source buffer
let mainSourceBuf: i8[200000] = 0;

function main(): i32 {
    // Print banner to stdout
    puts("=== TSN Compiler (Self-Hosted) ===");

    // Filename: input.tsn
    let fname: i8[20] = 0;
    fname[0] = 105; fname[1] = 110; fname[2] = 112;
    fname[3] = 117; fname[4] = 116; fname[5] = 46;
    fname[6] = 116; fname[7] = 115; fname[8] = 110;
    fname[9] = 0;

    let modeRb: i8[4] = 0;
    modeRb[0] = 114; modeRb[1] = 98; modeRb[2] = 0;

    // Open and read input file
    let inFile: ptr<i8> = fopen(addressof(fname[0]), addressof(modeRb[0]));
    if (inFile == null) {
        puts("Error: Cannot open input.tsn");
        return 1;
    }

    let bytesRead: i32 = fread(addressof(mainSourceBuf[0]), 1, 199999, inFile);
    fclose(inFile);

    puts("Read source OK");

    // Lexer
    lexer_init(addressof(mainSourceBuf[0]), bytesRead);
    let tokCount: i32 = tokenize();
    puts("Lexer OK");

    // Parser
    parser_init();
    let programNode: i32 = parse();
    puts("Parser OK");

    // Codegen (output goes to global output[] i32 array + outputSize)
    codegen_init();
    generate(programNode);
    puts("Codegen OK");

    // Output LLVM IR to stdout (each output[i] is a character code)
    // Redirect to file: UnifiedCompiler.exe > output.ll
    puts("--- LLVM IR BEGIN ---");
    let i: i32 = 0;
    while (i < outputSize) {
        putchar(output[i]);
        i = i + 1;
    }
    puts("--- LLVM IR END ---");

    puts("=== Compilation successful! ===");
    return 0;
}
"@

# Write output
$outputPath = "src/UnifiedCompiler.tsn"
Set-Content -Path $outputPath -Value $output -NoNewline

Write-Host "✅ Created $outputPath" -ForegroundColor Green

# Get stats
$lines = ($output -split "`n").Length
$chars = $output.Length
Write-Host "  Lines: $lines" -ForegroundColor Cyan
Write-Host "  Characters: $chars" -ForegroundColor Cyan

Write-Host "`nNow compiling with TypeScript compiler..." -ForegroundColor Cyan
Push-Location compiler-ts
deno run --allow-read --allow-write src/main.ts ../src/UnifiedCompiler.tsn UnifiedCompiler.ll
$compileResult = $LASTEXITCODE
Pop-Location

if ($compileResult -eq 0) {
    Write-Host "✅ Compilation successful!" -ForegroundColor Green
    Write-Host "`nNext steps:" -ForegroundColor Yellow
    Write-Host "  1. cd compiler-ts" -ForegroundColor White
    Write-Host "  2. clang UnifiedCompiler.ll -o UnifiedCompiler.exe" -ForegroundColor White
    Write-Host "  3. ./UnifiedCompiler.exe" -ForegroundColor White
} else {
    Write-Host "❌ Compilation failed" -ForegroundColor Red
    exit 1
}
